import qualified Data.Trie as T
import qualified Data.ByteString.Char8 as C8
import Data.Maybe
import Data.List
import Data.Function
import Data.Ord
import System.IO
import Data.Char
import qualified Data.List.Key as K
import Data.Map ((!), fromList, fromListWith, adjust, keys, Map, toList, lookup, insertWith, showTree)
import qualified Data.Array as A
import Text.PrettyPrint.Boxes

-- ----------------- Log processing code -------------------------

pts line band = foldl (+) 0 $ map weightedZone $ map getZones $ filterByBand band line
zones line band = foldl (+) 0 $ map weightedZone $ nub $ map getZones $ filterByBand band line
ctys line band = foldl (+) 0 $ map fst $ map weightedZone' $ uniqCty $ map getZonesDxcc $ filterByBand band line

zonesOld line band = length $ nub $ map getZones $ filterByBand band line
ctysOld line band = length $ map thd $ uniqCty $ map getZonesDxcc $ filterByBand band line

thd (_,_,x) = x

qsByBand line band = length $ nub $ map getCall $ filterByBand band line

filterQsos :: String -> [String]
filterQsos x = filter (isPrefixOf "QSO:") $ lines x

bandList =  ["10","15","20","40","80","160"]
processLogBands logFile = do
        inh <- openFile logFile ReadMode
        inpStr <- hGetContents inh
        putStrLn  $ "Points: " ++ (show $ map ( pts (filterQsos inpStr) ) bandList)
        putStrLn $ "QSOs: " ++ (show $ map ( qsByBand (filterQsos inpStr) ) bandList)
        putStrLn $ "CtyPts: " ++ (show $ map ( ctys (filterQsos inpStr) ) bandList)
        putStrLn $ "Dxcc: " ++ (show $  map ( ctysOld (filterQsos inpStr) ) bandList)
        putStrLn $ "ZonePts: " ++ (show $ map ( zones (filterQsos inpStr) ) bandList)
        putStrLn $ "Zones: " ++ (show $ map ( zonesOld (filterQsos inpStr) ) bandList)
        hClose inh

newPoints x = foldl (+) 0 $ map weightedZone $ map getZones $ filterQsos x
newCtyPts x = foldl (+) 0 $ map ( ctys (filterQsos x) ) bandList
newZonePts x = foldl (+) 0 $ map ( zones (filterQsos x) ) bandList

processLog logFile = 
    do
        inh <- openFile logFile ReadMode
        inpStr <- hGetContents inh
        let p = newPoints inpStr
            c = newCtyPts inpStr
            z = newZonePts inpStr
            in
            putStrLn $ show p ++ "\t" ++ show z ++ "\t" ++ show c ++ "\t" ++ show (p * (c + 4*z))
        hClose inh


totalPoints logFile = do
        inh <- openFile logFile ReadMode
        inpStr <- hGetContents inh
        print $ foldl (+) 0 $ map weightedZone $ map getZones $ filter (isPrefixOf "QSO:") $ lines inpStr
        hClose inh

pointsData logFile = do
        inh <- openFile logFile ReadMode
        inpStr <- hGetContents inh
        putStrLn $ unlines $ map show $ map weightedZone $ map getZones $ filter (isPrefixOf "QSO:") $ lines inpStr
        hClose inh

bandPoints band logFile = do
        inh <- openFile logFile ReadMode
        inpStr <- hGetContents inh
        printTable $ groupByN 10 $ map show $ map weightedZone $ map getZones $ filterByBand band $ filter (isPrefixOf "QSO:") $ lines inpStr
        hClose inh

bandCalls band logFile = do
        inh <- openFile logFile ReadMode
        inpStr <- hGetContents inh
        printTable $ groupByN 10 $ map getCall $ filterByBand band $ filter (isPrefixOf "QSO:") $ lines inpStr
        hClose inh

allZones logFile = do
			inh <- openFile logFile ReadMode
			inpStr <- hGetContents inh
			putStrLn $ unlines $ map show $ map weightedZone $ nub $ map getZones $ filter (isPrefixOf "QSO:") $ lines inpStr
			hClose inh

bandZones band logFile = do
			inh <- openFile logFile ReadMode
			inpStr <- hGetContents inh
			putStrLn $ unlines $ map show $ map weightedZone $ nub $ map getZones $ filterByBand band $ filter (isPrefixOf "QSO:") $ lines inpStr
			hClose inh

totalZMByBand logFile = do
			inh <- openFile logFile ReadMode
			inpStr <- hGetContents inh
			print $ foldl (+) 0 $ map weightedZone $ nub $ map getZones $ filterByBand "10" $ filter (isPrefixOf "QSO:") $ lines inpStr
			print $ foldl (+) 0 $ map weightedZone $ nub $ map getZones $ filterByBand "15" $ filter (isPrefixOf "QSO:") $ lines inpStr
			print $ foldl (+) 0 $ map weightedZone $ nub $ map getZones $ filterByBand "20" $ filter (isPrefixOf "QSO:") $ lines inpStr
			print $ foldl (+) 0 $ map weightedZone $ nub $ map getZones $ filterByBand "40" $ filter (isPrefixOf "QSO:") $ lines inpStr
			print $ foldl (+) 0 $ map weightedZone $ nub $ map getZones $ filterByBand "80" $ filter (isPrefixOf "QSO:") $ lines inpStr
			print $ foldl (+) 0 $ map weightedZone $ nub $ map getZones $ filterByBand "160" $ filter (isPrefixOf "QSO:") $ lines inpStr
			hClose inh

totalZM logFile = do
			inh <- openFile logFile ReadMode
			inpStr <- hGetContents inh
			print $ foldl (+) 0 $ map ( zones (filter (isPrefixOf "QSO:") $ lines inpStr) ) ["10","15","20","40","80","160"]
			hClose inh
			
allDxcc logFile = do
			inh <- openFile logFile ReadMode
			inpStr <- hGetContents inh
			putStrLn $ unlines $ map show $ map weightedZone' $ uniqCty $ map getZonesDxcc $ filter (isPrefixOf "QSO:") $ lines inpStr
			hClose inh

uniqCty xs = nubBy eqThird xs
   where eqThird (x1, y1, z1) (x2, y2, z2) = z1 == z2
   
bandCty band logFile = do
			inh <- openFile logFile ReadMode
			inpStr <- hGetContents inh
			printTable $ groupByN 10 $ map show $ map weightedZone' $ uniqCty $ map getZonesDxcc $ filterByBand band $ filter (isPrefixOf "QSO:") $ lines inpStr
			hClose inh

totalDM logFile = do
			inh <- openFile logFile ReadMode
			inpStr <- hGetContents inh
			print $ foldl (+) 0 $ map ( ctys (filter (isPrefixOf "QSO:") $ lines inpStr) ) ["10","15","20","40","80","160"]
			hClose inh
			
totalDMByBand logFile = do
			inh <- openFile logFile ReadMode
			inpStr <- hGetContents inh
			print $ ctys (filter (isPrefixOf "QSO:") $ lines inpStr) "10"
			print $ ctys (filter (isPrefixOf "QSO:") $ lines inpStr) "15"
			print $ ctys (filter (isPrefixOf "QSO:") $ lines inpStr) "20"
			print $ ctys (filter (isPrefixOf "QSO:") $ lines inpStr) "40"
			print $ ctys (filter (isPrefixOf "QSO:") $ lines inpStr) "80"
			print $ ctys (filter (isPrefixOf "QSO:") $ lines inpStr) "160"
			hClose inh
			
weightedZone' (from, to, cty) = (factorArray A.! (from, to), cty)

getZonesDxcc logLine = (read (getZoneSnt logLine) :: Int, read (getZoneRcvd logLine) :: Int, getDxcc $ getCall logLine)

weightedZone :: (Int, Int) -> Int
weightedZone (from, to) = factorArray A.! (from, to)

getZoneRcvd :: String -> String
getZoneRcvd logLine = trim $ take 2 $ drop 73 logLine

getZoneRcvdInt :: String -> Int
getZoneRcvdInt logLine = read (getZoneRcvd logLine) :: Int

getZoneSnt :: String -> String
getZoneSnt logLine = trim $ take 2 $ drop 48 logLine

getZoneSntInt :: String -> Int
getZoneSntInt logLine = read (getZoneSnt logLine) :: Int

getZones logLine = (read (getZoneSnt logLine) :: Int, read (getZoneRcvd logLine) :: Int) 

-- --------------------- Printing code ------------------------------

groupByN :: Int -> [a] -> [[a]]
groupByN _ [] = []
groupByN n l
  | n > 0 = (take n l) : (groupByN n (drop n l))
  | otherwise = error "Negative n"

printTable :: [[String]] -> IO ()
printTable rows = printBox $ hsep 2 left (map (vcat left . map text) (transpose rows))

-- --------------------- Band-related code ------------------------------

filterByBand :: String -> [String] -> [String]
filterByBand _ [] = []
filterByBand band (x:xs)	| (getBand (getFreq x) == band) = x:filterByBand band xs
							| otherwise						= filterByBand band xs

getFreq :: String -> Int
getFreq logLine = read (trim $ take 5 $ drop 5 logLine) :: Int

getBand :: Int -> String
getBand freq | (1799 < freq) && (freq < 2000) = "160"
             | (3499 < freq) && (freq < 4000) = "80"
             | (6999 < freq) && (freq < 7500) = "40"
             | (13999 < freq) && (freq < 15000) = "20"
             | (20999 < freq) && (freq < 22000) = "15"
             | (27999 < freq) && (freq < 30000) = "10"
             | otherwise = ""
			 
-- --------------------- Graph code ------------------------------
buildGraph :: Ord a => [(a, a, Int)] -> Map a [(a, Int)]
buildGraph g = fromListWith (++) $ g >>=
               \(a,b,d) -> [(a,[(b,d)]), (b,[(a,d)])]
			   
dijkstra :: Ord a => a -> Map a [(a, Int)] -> Map a (Int, Maybe a)
dijkstra source graph =
    f (fromList [(v, (if v == source then 0 else 9999999, Nothing)) 
                | v <- keys graph]) (keys graph) where
    f ds [] = ds
    f ds q  = f (foldr relax ds $ graph ! m) (delete m q) where
              m = K.minimum (fst . (ds !)) q
              relax (e,d) = adjust (min (fst (ds ! m) + d, Just m)) e
			  
shortestPath :: Ord a => a -> a -> Map a [(a, Int)] -> [a]
shortestPath from to graph = reverse $ f to where
    f x = x : maybe [] f (snd $ dijkstra from graph ! x)
	
pickD (x,(y,z)) = y
tableRow zone graph = show' $ map succ $ map pickD $ toList $ dijkstra zone graph
tableRowList zone graph =  map succ $ map pickD $ toList $ dijkstra zone graph
tableRowZoneList zone = tableRowList zone zoneGraph
tableList = concat $ map tableRowZoneList [1..40]

factorArray = A.listArray ((1,1),(40,40)) tableList

tableRowCQ z = tableRow z zoneGraph

table = putStr $ unlines $ map tableRowCQ [1..40]

show' :: Show a => [a] -> String
show' = intercalate "  " . map show

path x y = shortestPath x y zoneGraph
								 
paths x = [(x, y, path x y) | y <- [1..40]]

-- --------------------- DXCC code ---------------------------------
testDxcc = do
        inh <- openFile "ve7sv.log" ReadMode
        inpStr <- hGetContents inh
        putStrLn $ unlines $ map getDxcc $ map getCall $ filter (isPrefixOf "QSO:") $ lines inpStr
        hClose inh

getCall :: String -> String
getCall logLine = trim $ take 14 $ drop 55 logLine

isSlashNumCall call = (isDigit $ last call) && ((=='/') (call !! (length call - 2)))
isSlashAPM call = (isSuffixOf "/A" call) || (isSuffixOf "/P" call) || (isSuffixOf "/M" call)
isSlashQRP call = isSuffixOf "/QRP" call

adjustSlashNum call = (minimumBy (comparing length) $ wordsWhen isDigit call) ++ [(last call)]
getSlashCty call = minimumBy (comparing length) $ wordsWhen (=='/') call

adjustSlash call 
			| isSlashQRP call 		= take (length call - 4) call
			| isSlashAPM call 		= take (length call - 2) call
			| isSlashNumCall call	= adjustSlashNum call
			| elem '/' call			= getSlashCty call
			| otherwise 			= call

invert m = fromListWith (++) pairs
   where pairs = [(v,[k]) | (k,vs) <- toList m, v<-vs]
   
getExactCty call = Data.Map.lookup call $ invert $ fromList exactMapString

trim :: String -> String
trim = f . f where f = reverse . dropWhile isSpace

getSnd (_, x, _) = x

getCty call = T.match ctyData $ C8.pack $ adjustSlash call

getDxcc call
		| (isNothing $ getExactCty call) && (isNothing $ getCty call) = "UNKNOWN_DXCC"
		| isNothing $ getExactCty call 	= getSnd $ fromJust $ getCty call
		| otherwise 					= head $ fromJust $ getExactCty call

wordsWhen     :: (Char -> Bool) -> String -> [String]
wordsWhen p s =  case dropWhile p s of
                      "" -> []
                      s' -> w : wordsWhen p s''
                            where (w, s'') = break p s'

-- ------------------------- Graph data -------------------------
zoneGraph = buildGraph 
						[(1,2,1),(1,3,1),(1,4,1),(1,19,2),(1,31,2),
						(2,4,1),(2,5,1),(2,40,1),
						(3,4,1),(3,6,1),(3,31,2),
						(4,5,1),(4,6,1),
						(5,8,1),(5,14,2),(5,33,2),(5,40,1),
						(6,7,1),(6,8,1),(6,31,2),
						(7,8,1),(7,9,1),(7,10,1),(7,31,2),
						(8,9,1),(8,33,2),(8,35,2),
						(9,10,1),(9,11,1),(9,35,2),
						(10,11,1),(10,12,1),(10,13,1),(10,31,2),(10,32,2),
						(11,13,1),(11,35,2),(11,36,2),(11,38,2),
						(12,13,1),(12,32,2),
						(13,38,2),
						(14,15,1),(14,16,1),(14,33,1),(14,40,2),
						(15,16,1),(15,20,1),(15,33,1),(15,34,1),
						(16,17,1),(16,20,1),(16,21,1),(16,40,2),
						(17,18,1),(17,21,1),(17,23,1),
						(18,19,1),(18,23,1),
						(19,23,1),(19,24,1),(19,25,1),(19,27,2),(19,31,2),
						(20,21,1),(20,34,1),
						(21,22,1),(21,23,1),(21,34,1),(21,37,1),
						(22,23,1),(22,26,1),(22,28,1),(22,29,2),(22,37,1),(22,39,2),
						(23,24,1),
						(24,25,1),(24,26,1),(24,27,1),
						(25,27,1),
						(26,27,1),(26,28,1),
						(27,28,1),(27,31,2),
						(28,29,1),(28,30,1),(28,31,2),
						(29,30,1),(29,39,2),
						(30,32,1),
						(31,32,2),
						(33,34,1),(33,35,1),
						(34,35,1),(34,36,1),(34,37,1),
						(35,36,1),
						(36,37,1),(36,38,1),
						(37,38,1),(37,39,1),
						(38,39,1)]

-- ------------------------- DXCC data -------------------------
ctyData = T.fromList [(C8.pack "1A","1A"),
					(C8.pack "1S","1S"),
					(C8.pack "9M0","1S"),
					(C8.pack "BV9S","1S"),
					(C8.pack "3A","3A"),
					(C8.pack "3B6","3B6"),
					(C8.pack "3B7","3B6"),
					(C8.pack "3B8","3B8"),
					(C8.pack "3B9","3B9"),
					(C8.pack "3C","3C"),
					(C8.pack "3C0","3C0"),
					(C8.pack "3D2","3D2"),
					(C8.pack "3DA","3DA"),
					(C8.pack "3V","3V"),
					(C8.pack "TS","3V"),
					(C8.pack "3W","3W"),
					(C8.pack "XV","3W"),
					(C8.pack "3X","3X"),
					(C8.pack "4J","4J"),
					(C8.pack "4K","4J"),
					(C8.pack "4L","4L"),
					(C8.pack "UF6V","4L"),
					(C8.pack "4O","4O"),
					(C8.pack "4P","4S"),
					(C8.pack "4Q","4S"),
					(C8.pack "4R","4S"),
					(C8.pack "4U0I","4U1I"),
					(C8.pack "4U1I","4U1I"),
					(C8.pack "4U2I","4U1I"),
					(C8.pack "4U3I","4U1I"),
					(C8.pack "4U4I","4U1I"),
					(C8.pack "4U5I","4U1I"),
					(C8.pack "4U6I","4U1I"),
					(C8.pack "4U7I","4U1I"),
					(C8.pack "4U8I","4U1I"),
					(C8.pack "4U9I","4U1I"),
					(C8.pack "4U1U","4U1U"),
					(C8.pack "4U1V","4U1V"),
					(C8.pack "4W","4W"),
					(C8.pack "4X","4X"),
					(C8.pack "4Z","4X"),
					(C8.pack "5A","5A"),
					(C8.pack "5B","5B"),
					(C8.pack "C4","5B"),
					(C8.pack "H2","5B"),
					(C8.pack "P3","5B"),
					(C8.pack "5H","5H"),
					(C8.pack "5I","5H"),
					(C8.pack "5N","5N"),
					(C8.pack "5O","5N"),
					(C8.pack "5R","5R"),
					(C8.pack "5S","5R"),
					(C8.pack "6X","5R"),
					(C8.pack "5T","5T"),
					(C8.pack "5U","5U"),
					(C8.pack "5V","5V"),
					(C8.pack "5W","5W"),
					(C8.pack "5X","5X"),
					(C8.pack "5Y","5Z"),
					(C8.pack "5Z","5Z"),
					(C8.pack "6V","6W"),
					(C8.pack "6W","6W"),
					(C8.pack "6Y","6Y"),
					(C8.pack "7O","7O"),
					(C8.pack "7P","7P"),
					(C8.pack "7Q","7Q"),
					(C8.pack "7R","7X"),
					(C8.pack "7T","7X"),
					(C8.pack "7U","7X"),
					(C8.pack "7V","7X"),
					(C8.pack "7W","7X"),
					(C8.pack "7X","7X"),
					(C8.pack "7Y","7X"),
					(C8.pack "8P","8P"),
					(C8.pack "8Q","8Q"),
					(C8.pack "8R","8R"),
					(C8.pack "9A","9A"),
					(C8.pack "9G","9G"),
					(C8.pack "9H","9H"),
					(C8.pack "9I","9J"),
					(C8.pack "9J","9J"),
					(C8.pack "9K","9K"),
					(C8.pack "9L","9L"),
					(C8.pack "9M2","9M2"),
					(C8.pack "9M4","9M2"),
					(C8.pack "9W2","9M2"),
					(C8.pack "9W4","9M2"),
					(C8.pack "9M6","9M6"),
					(C8.pack "9M8","9M6"),
					(C8.pack "9M9","9M6"),
					(C8.pack "9W6","9M6"),
					(C8.pack "9W8","9M6"),
					(C8.pack "9N","9N"),
					(C8.pack "9O","9Q"),
					(C8.pack "9P","9Q"),
					(C8.pack "9Q","9Q"),
					(C8.pack "9R","9Q"),
					(C8.pack "9S","9Q"),
					(C8.pack "9T","9Q"),
					(C8.pack "9U","9U"),
					(C8.pack "9V","9V"),
					(C8.pack "S6","9V"),
					(C8.pack "9X","9X"),
					(C8.pack "9Y","9Y"),
					(C8.pack "9Z","9Y"),
					(C8.pack "8O","A2"),
					(C8.pack "A2","A2"),
					(C8.pack "A3","A3"),
					(C8.pack "A4","A4"),
					(C8.pack "A5","A5"),
					(C8.pack "A6","A6"),
					(C8.pack "A7","A7"),
					(C8.pack "A9","A9"),
					(C8.pack "6P","AP"),
					(C8.pack "6Q","AP"),
					(C8.pack "6R","AP"),
					(C8.pack "6S","AP"),
					(C8.pack "AP","AP"),
					(C8.pack "AQ","AP"),
					(C8.pack "AR","AP"),
					(C8.pack "AS","AP"),
					(C8.pack "BM","BV"),
					(C8.pack "BN","BV"),
					(C8.pack "BO","BV"),
					(C8.pack "BP","BV"),
					(C8.pack "BQ","BV"),
					(C8.pack "BU","BV"),
					(C8.pack "BV","BV"),
					(C8.pack "BW","BV"),
					(C8.pack "BX","BV"),
					(C8.pack "BM9P","BV9P"),
					(C8.pack "BN9P","BV9P"),
					(C8.pack "BO9P","BV9P"),
					(C8.pack "BP9P","BV9P"),
					(C8.pack "BQ9P","BV9P"),
					(C8.pack "BU9P","BV9P"),
					(C8.pack "BV9P","BV9P"),
					(C8.pack "BW9P","BV9P"),
					(C8.pack "BX9P","BV9P"),
					(C8.pack "3H","BY"),
					(C8.pack "3I","BY"),
					(C8.pack "3J","BY"),
					(C8.pack "3K","BY"),
					(C8.pack "3L","BY"),
					(C8.pack "3M","BY"),
					(C8.pack "3N","BY"),
					(C8.pack "3O","BY"),
					(C8.pack "3P","BY"),
					(C8.pack "3Q","BY"),
					(C8.pack "3R","BY"),
					(C8.pack "3S","BY"),
					(C8.pack "3T","BY"),
					(C8.pack "3U","BY"),
					(C8.pack "B","BY"),
					(C8.pack "C2","C2"),
					(C8.pack "C3","C3"),
					(C8.pack "C5","C5"),
					(C8.pack "C6","C6"),
					(C8.pack "C8","C9"),
					(C8.pack "C9","C9"),
					(C8.pack "3G","CE"),
					(C8.pack "CA","CE"),
					(C8.pack "CB","CE"),
					(C8.pack "CC","CE"),
					(C8.pack "CD","CE"),
					(C8.pack "CE","CE"),
					(C8.pack "XQ","CE"),
					(C8.pack "XR","CE"),
					(C8.pack "3G0X","CE0X"),
					(C8.pack "CA0X","CE0X"),
					(C8.pack "CB0X","CE0X"),
					(C8.pack "CC0X","CE0X"),
					(C8.pack "CD0X","CE0X"),
					(C8.pack "CE0X","CE0X"),
					(C8.pack "XQ0X","CE0X"),
					(C8.pack "XR0X","CE0X"),
					(C8.pack "3G0","CE0Y"),
					(C8.pack "CA0","CE0Y"),
					(C8.pack "CB0","CE0Y"),
					(C8.pack "CC0","CE0Y"),
					(C8.pack "CD0","CE0Y"),
					(C8.pack "CE0","CE0Y"),
					(C8.pack "XQ0","CE0Y"),
					(C8.pack "XR0","CE0Y"),
					(C8.pack "3G0Z","CE0Z"),
					(C8.pack "CA0Z","CE0Z"),
					(C8.pack "CB0Z","CE0Z"),
					(C8.pack "CC0Z","CE0Z"),
					(C8.pack "CD0Z","CE0Z"),
					(C8.pack "CE0Z","CE0Z"),
					(C8.pack "XQ0Z","CE0Z"),
					(C8.pack "XR0Z","CE0Z"),
					(C8.pack "3Y","CE9"),
					(C8.pack "AX0","CE9"),
					(C8.pack "AY1Z","CE9"),
					(C8.pack "AY2Z","CE9"),
					(C8.pack "AY3Z","CE9"),
					(C8.pack "AY4Z","CE9"),
					(C8.pack "AY5Z","CE9"),
					(C8.pack "AY6Z","CE9"),
					(C8.pack "AY7Z","CE9"),
					(C8.pack "AY8Z","CE9"),
					(C8.pack "AY9Z","CE9"),
					(C8.pack "FT0Y","CE9"),
					(C8.pack "FT1Y","CE9"),
					(C8.pack "FT2Y","CE9"),
					(C8.pack "FT3Y","CE9"),
					(C8.pack "FT4Y","CE9"),
					(C8.pack "FT5Y","CE9"),
					(C8.pack "FT6Y","CE9"),
					(C8.pack "FT7Y","CE9"),
					(C8.pack "FT8Y","CE9"),
					(C8.pack "FT9Y","CE9"),
					(C8.pack "LU1Z","CE9"),
					(C8.pack "LU2Z","CE9"),
					(C8.pack "LU3Z","CE9"),
					(C8.pack "LU4Z","CE9"),
					(C8.pack "LU5Z","CE9"),
					(C8.pack "LU6Z","CE9"),
					(C8.pack "LU7Z","CE9"),
					(C8.pack "LU8Z","CE9"),
					(C8.pack "LU9Z","CE9"),
					(C8.pack "R1AN","CE9"),
					(C8.pack "RI1A","CE9"),
					(C8.pack "VI0","CE9"),
					(C8.pack "VK0","CE9"),
					(C8.pack "ZL5","CE9"),
					(C8.pack "ZM5","CE9"),
					(C8.pack "ZS7","CE9"),
					(C8.pack "CL","CO"),
					(C8.pack "CM","CO"),
					(C8.pack "CO","CO"),
					(C8.pack "T4","CO"),
					(C8.pack "5C","CN"),
					(C8.pack "5D","CN"),
					(C8.pack "5E","CN"),
					(C8.pack "5F","CN"),
					(C8.pack "5G","CN"),
					(C8.pack "CN","CN"),
					(C8.pack "CP","CP"),
					(C8.pack "CQ","CT"),
					(C8.pack "CR","CT"),
					(C8.pack "CS","CT"),
					(C8.pack "CT","CT"),
					(C8.pack "CQ2","CT3"),
					(C8.pack "CQ3","CT3"),
					(C8.pack "CQ9","CT3"),
					(C8.pack "CR3","CT3"),
					(C8.pack "CR9","CT3"),
					(C8.pack "CS3","CT3"),
					(C8.pack "CS9","CT3"),
					(C8.pack "CT3","CT3"),
					(C8.pack "CT9","CT3"),
					(C8.pack "CQ1","CU"),
					(C8.pack "CQ8","CU"),
					(C8.pack "CR1","CU"),
					(C8.pack "CR2","CU"),
					(C8.pack "CR8","CU"),
					(C8.pack "CS4","CU"),
					(C8.pack "CS8","CU"),
					(C8.pack "CT8","CU"),
					(C8.pack "CU","CU"),
					(C8.pack "CV","CX"),
					(C8.pack "CW","CX"),
					(C8.pack "CX","CX"),
					(C8.pack "CY0","CY0"),
					(C8.pack "CY9","CY9"),
					(C8.pack "D2","D2"),
					(C8.pack "D3","D2"),
					(C8.pack "D4","D4"),
					(C8.pack "D6","D6"),
					(C8.pack "DA","DL"),
					(C8.pack "DB","DL"),
					(C8.pack "DC","DL"),
					(C8.pack "DD","DL"),
					(C8.pack "DE","DL"),
					(C8.pack "DF","DL"),
					(C8.pack "DG","DL"),
					(C8.pack "DH","DL"),
					(C8.pack "DI","DL"),
					(C8.pack "DJ","DL"),
					(C8.pack "DK","DL"),
					(C8.pack "DL","DL"),
					(C8.pack "DM","DL"),
					(C8.pack "DN","DL"),
					(C8.pack "DO","DL"),
					(C8.pack "DP","DL"),
					(C8.pack "DQ","DL"),
					(C8.pack "DR","DL"),
					(C8.pack "4D","DU"),
					(C8.pack "4E","DU"),
					(C8.pack "4F","DU"),
					(C8.pack "4G","DU"),
					(C8.pack "4H","DU"),
					(C8.pack "4I","DU"),
					(C8.pack "DU","DU"),
					(C8.pack "DV","DU"),
					(C8.pack "DW","DU"),
					(C8.pack "DX","DU"),
					(C8.pack "DY","DU"),
					(C8.pack "DZ","DU"),
					(C8.pack "E3","E3"),
					(C8.pack "E4","E4"),
					(C8.pack "E5","E5/s"),
					(C8.pack "E6","E6"),
					(C8.pack "E7","E7"),
					(C8.pack "AM","EA"),
					(C8.pack "AN","EA"),
					(C8.pack "AO","EA"),
					(C8.pack "EA","EA"),
					(C8.pack "EB","EA"),
					(C8.pack "EC","EA"),
					(C8.pack "ED","EA"),
					(C8.pack "EE","EA"),
					(C8.pack "EF","EA"),
					(C8.pack "EG","EA"),
					(C8.pack "EH","EA"),
					(C8.pack "AM6","EA6"),
					(C8.pack "AN6","EA6"),
					(C8.pack "AO6","EA6"),
					(C8.pack "EA6","EA6"),
					(C8.pack "EB6","EA6"),
					(C8.pack "EC6","EA6"),
					(C8.pack "ED6","EA6"),
					(C8.pack "EE6","EA6"),
					(C8.pack "EF6","EA6"),
					(C8.pack "EG6","EA6"),
					(C8.pack "EH6","EA6"),
					(C8.pack "AM8","EA8"),
					(C8.pack "AN8","EA8"),
					(C8.pack "AO8","EA8"),
					(C8.pack "EA8","EA8"),
					(C8.pack "EB8","EA8"),
					(C8.pack "EC8","EA8"),
					(C8.pack "ED8","EA8"),
					(C8.pack "EE8","EA8"),
					(C8.pack "EF8","EA8"),
					(C8.pack "EG8","EA8"),
					(C8.pack "EH8","EA8"),
					(C8.pack "AM9","EA9"),
					(C8.pack "AN9","EA9"),
					(C8.pack "AO9","EA9"),
					(C8.pack "EA9","EA9"),
					(C8.pack "EB9","EA9"),
					(C8.pack "EC9","EA9"),
					(C8.pack "ED9","EA9"),
					(C8.pack "EE9","EA9"),
					(C8.pack "EF9","EA9"),
					(C8.pack "EG9","EA9"),
					(C8.pack "EH9","EA9"),
					(C8.pack "EI","EI"),
					(C8.pack "EJ","EI"),
					(C8.pack "EK","EK"),
					(C8.pack "5L","EL"),
					(C8.pack "5M","EL"),
					(C8.pack "6Z","EL"),
					(C8.pack "A8","EL"),
					(C8.pack "D5","EL"),
					(C8.pack "EL","EL"),
					(C8.pack "9B","EP"),
					(C8.pack "9C","EP"),
					(C8.pack "9D","EP"),
					(C8.pack "EP","EP"),
					(C8.pack "EQ","EP"),
					(C8.pack "ER","ER"),
					(C8.pack "ES","ES"),
					(C8.pack "9E","ET"),
					(C8.pack "9F","ET"),
					(C8.pack "ET","ET"),
					(C8.pack "EU","EU"),
					(C8.pack "EV","EU"),
					(C8.pack "EW","EU"),
					(C8.pack "EX","EX"),
					(C8.pack "EY","EY"),
					(C8.pack "EZ","EZ"),
					(C8.pack "F","F"),
					(C8.pack "HW","F"),
					(C8.pack "HX","F"),
					(C8.pack "HY","F"),
					(C8.pack "TH","F"),
					(C8.pack "TM","F"),
					(C8.pack "TP","F"),
					(C8.pack "TQ","F"),
					(C8.pack "TV","F"),
					(C8.pack "FG","FG"),
					(C8.pack "FH","FH"),
					(C8.pack "FJ","FJ"),
					(C8.pack "FK","FK"),
					(C8.pack "TX1","FK"),
					(C8.pack "FM","FM"),
					(C8.pack "FO","FO"),
					(C8.pack "FP","FP"),
					(C8.pack "FR","FR"),
					(C8.pack "FT5G","FR/g"),
					(C8.pack "FT5E","FR/j"),
					(C8.pack "FT5J","FR/j"),
					(C8.pack "FT5T","FR/t"),
					(C8.pack "FS","FS"),
					(C8.pack "FT0W","FT5W"),
					(C8.pack "FT1W","FT5W"),
					(C8.pack "FT2W","FT5W"),
					(C8.pack "FT4W","FT5W"),
					(C8.pack "FT5W","FT5W"),
					(C8.pack "FT8W","FT5W"),
					(C8.pack "FT0X","FT5X"),
					(C8.pack "FT1X","FT5X"),
					(C8.pack "FT2X","FT5X"),
					(C8.pack "FT4X","FT5X"),
					(C8.pack "FT5X","FT5X"),
					(C8.pack "FT8X","FT5X"),
					(C8.pack "FT0Z","FT5Z"),
					(C8.pack "FT1Z","FT5Z"),
					(C8.pack "FT2Z","FT5Z"),
					(C8.pack "FT4Z","FT5Z"),
					(C8.pack "FT5Z","FT5Z"),
					(C8.pack "FT8Z","FT5Z"),
					(C8.pack "FW","FW"),
					(C8.pack "TW","FW"),
					(C8.pack "FY","FY"),
					(C8.pack "2","G"),
					(C8.pack "G","G"),
					(C8.pack "M","G"),
					(C8.pack "ZH","G"),
					(C8.pack "ZI","G"),
					(C8.pack "ZJ","G"),
					(C8.pack "2D","GD"),
					(C8.pack "2T","GD"),
					(C8.pack "GD","GD"),
					(C8.pack "GT","GD"),
					(C8.pack "MD","GD"),
					(C8.pack "MT","GD"),
					(C8.pack "2I","GI"),
					(C8.pack "2N","GI"),
					(C8.pack "GI","GI"),
					(C8.pack "GN","GI"),
					(C8.pack "MI","GI"),
					(C8.pack "MN","GI"),
					(C8.pack "2H","GJ"),
					(C8.pack "2J","GJ"),
					(C8.pack "GH","GJ"),
					(C8.pack "GJ","GJ"),
					(C8.pack "MH","GJ"),
					(C8.pack "MJ","GJ"),
					(C8.pack "2A","GM"),
					(C8.pack "2M","GM"),
					(C8.pack "2S","GM"),
					(C8.pack "GA","GM"),
					(C8.pack "GM","GM"),
					(C8.pack "GS","GM"),
					(C8.pack "MA","GM"),
					(C8.pack "MM","GM"),
					(C8.pack "MS","GM"),
					(C8.pack "2Z","GM/s"),
					(C8.pack "GZ","GM/s"),
					(C8.pack "MZ","GM/s"),
					(C8.pack "2P","GU"),
					(C8.pack "2U","GU"),
					(C8.pack "GP","GU"),
					(C8.pack "GU","GU"),
					(C8.pack "MP","GU"),
					(C8.pack "MU","GU"),
					(C8.pack "2C","GW"),
					(C8.pack "2W","GW"),
					(C8.pack "2X","GW"),
					(C8.pack "2Y","GW"),
					(C8.pack "GC","GW"),
					(C8.pack "GW","GW"),
					(C8.pack "MC","GW"),
					(C8.pack "MW","GW"),
					(C8.pack "H4","H4"),
					(C8.pack "H40","H40"),
					(C8.pack "HA","HA"),
					(C8.pack "HG","HA"),
					(C8.pack "HB","HB"),
					(C8.pack "HE","HB"),
					(C8.pack "HB0","HB0"),
					(C8.pack "HE0","HB0"),
					(C8.pack "HC","HC"),
					(C8.pack "HD","HC"),
					(C8.pack "HC8","HC8"),
					(C8.pack "HD8","HD8"),
					(C8.pack "4V","HH"),
					(C8.pack "HH","HH"),
					(C8.pack "HI","HI"),
					(C8.pack "5J","HK"),
					(C8.pack "5K","HK"),
					(C8.pack "HJ","HK"),
					(C8.pack "HK","HK"),
					(C8.pack "5J0","HK0"),
					(C8.pack "5K0","HK0"),
					(C8.pack "HJ0","HK0"),
					(C8.pack "HK0","HK0"),
					(C8.pack "5J0M","HK0M"),
					(C8.pack "5K0M","HK0M"),
					(C8.pack "HJ0M","HK0M"),
					(C8.pack "HK0M","HK0M"),
					(C8.pack "6K","HL"),
					(C8.pack "6L","HL"),
					(C8.pack "6M","HL"),
					(C8.pack "6N","HL"),
					(C8.pack "D7","HL"),
					(C8.pack "D8","HL"),
					(C8.pack "D9","HL"),
					(C8.pack "DS","HL"),
					(C8.pack "DT","HL"),
					(C8.pack "HL","HL"),
					(C8.pack "KL9K","HL"),
					(C8.pack "3E","HP"),
					(C8.pack "3F","HP"),
					(C8.pack "H3","HP"),
					(C8.pack "H8","HP"),
					(C8.pack "H9","HP"),
					(C8.pack "HO","HP"),
					(C8.pack "HP","HP"),
					(C8.pack "HQ","HR"),
					(C8.pack "HR","HR"),
					(C8.pack "E2","HS"),
					(C8.pack "HS","HS"),
					(C8.pack "HV","HV"),
					(C8.pack "7Z","HZ"),
					(C8.pack "8Z","HZ"),
					(C8.pack "HZ","HZ"),
					(C8.pack "I","I"),
					(C8.pack "IG9","IG9"),
					(C8.pack "IH9","IG9"),
					(C8.pack "IM0","IS"),
					(C8.pack "IS","IS"),
					(C8.pack "IW0U","IS"),
					(C8.pack "IW0V","IS"),
					(C8.pack "IW0W","IS"),
					(C8.pack "IW0X","IS"),
					(C8.pack "IW0Y","IS"),
					(C8.pack "IW0Z","IS"),
					(C8.pack "IB9","IT9"),
					(C8.pack "ID9","IT9"),
					(C8.pack "IE9","IT9"),
					(C8.pack "IF9","IT9"),
					(C8.pack "II9","IT9"),
					(C8.pack "IJ9","IT9"),
					(C8.pack "IO9","IT9"),
					(C8.pack "IQ9","IT9"),
					(C8.pack "IR9","IT9"),
					(C8.pack "IT9","IT9"),
					(C8.pack "IU9","IT9"),
					(C8.pack "IW9","IT9"),
					(C8.pack "J2","J2"),
					(C8.pack "J3","J3"),
					(C8.pack "J5","J5"),
					(C8.pack "J6","J6"),
					(C8.pack "J7","J7"),
					(C8.pack "J8","J8"),
					(C8.pack "7J","JA"),
					(C8.pack "7K","JA"),
					(C8.pack "7L","JA"),
					(C8.pack "7M","JA"),
					(C8.pack "7N","JA"),
					(C8.pack "8J","JA"),
					(C8.pack "8K","JA"),
					(C8.pack "8L","JA"),
					(C8.pack "8M","JA"),
					(C8.pack "8N","JA"),
					(C8.pack "JA","JA"),
					(C8.pack "JE","JA"),
					(C8.pack "JF","JA"),
					(C8.pack "JG","JA"),
					(C8.pack "JH","JA"),
					(C8.pack "JI","JA"),
					(C8.pack "JJ","JA"),
					(C8.pack "JK","JA"),
					(C8.pack "JL","JA"),
					(C8.pack "JM","JA"),
					(C8.pack "JN","JA"),
					(C8.pack "JO","JA"),
					(C8.pack "JP","JA"),
					(C8.pack "JQ","JA"),
					(C8.pack "JR","JA"),
					(C8.pack "JS","JA"),
					(C8.pack "JD1","JD1/o"),
					(C8.pack "JT","JT"),
					(C8.pack "JU","JT"),
					(C8.pack "JV","JT"),
					(C8.pack "JW","JW"),
					(C8.pack "JX","JX"),
					(C8.pack "JY","JY"),
					(C8.pack "AA","K"),
					(C8.pack "AB","K"),
					(C8.pack "AC","K"),
					(C8.pack "AD","K"),
					(C8.pack "AE","K"),
					(C8.pack "AF","K"),
					(C8.pack "AG","K"),
					(C8.pack "AI","K"),
					(C8.pack "AJ","K"),
					(C8.pack "AK","K"),
					(C8.pack "K","K"),
					(C8.pack "N","K"),
					(C8.pack "W","K"),
					(C8.pack "KG4","KG4"),
					(C8.pack "AH0","KH0"),
					(C8.pack "KH0","KH0"),
					(C8.pack "NH0","KH0"),
					(C8.pack "WH0","KH0"),
					(C8.pack "AH1","KH0"),
					(C8.pack "KH1","KH1"),
					(C8.pack "NH1","KH1"),
					(C8.pack "WH1","KH1"),
					(C8.pack "AH2","KH2"),
					(C8.pack "KH2","KH2"),
					(C8.pack "NH2","KH2"),
					(C8.pack "WH2","KH2"),
					(C8.pack "AH3","KH3"),
					(C8.pack "KH3","KH3"),
					(C8.pack "NH3","KH3"),
					(C8.pack "WH3","KH3"),
					(C8.pack "AH4","KH4"),
					(C8.pack "KH4","KH4"),
					(C8.pack "NH4","KH4"),
					(C8.pack "WH4","KH4"),
					(C8.pack "AH5","KH5"),
					(C8.pack "KH5","KH5"),
					(C8.pack "NH5","KH5"),
					(C8.pack "WH5","KH5"),
					(C8.pack "AH6","KH6"),
					(C8.pack "AH7","KH6"),
					(C8.pack "KH6","KH6"),
					(C8.pack "KH7","KH6"),
					(C8.pack "NH6","KH6"),
					(C8.pack "NH7","KH6"),
					(C8.pack "WH6","KH6"),
					(C8.pack "WH7","KH6"),
					(C8.pack "AH7K","KH7K"),
					(C8.pack "KH7K","KH7K"),
					(C8.pack "NH7K","KH7K"),
					(C8.pack "WH7K","KH7K"),
					(C8.pack "AH8","KH8"),
					(C8.pack "KH8","KH8"),
					(C8.pack "NH8","KH8"),
					(C8.pack "WH8","KH8"),
					(C8.pack "AH9","KH9"),
					(C8.pack "KH9","KH9"),
					(C8.pack "NH9","KH9"),
					(C8.pack "WH9","KH9"),
					(C8.pack "AL","KL"),
					(C8.pack "KL","KL"),
					(C8.pack "NL","KL"),
					(C8.pack "WL","KL"),
					(C8.pack "KP1","KP1"),
					(C8.pack "NP1","KP1"),
					(C8.pack "WP1","KP1"),
					(C8.pack "KP2","KP2"),
					(C8.pack "NP2","KP2"),
					(C8.pack "WP2","KP2"),
					(C8.pack "KP3","KP4"),
					(C8.pack "KP4","KP4"),
					(C8.pack "NP3","KP4"),
					(C8.pack "NP4","KP4"),
					(C8.pack "WP3","KP4"),
					(C8.pack "WP4","KP4"),
					(C8.pack "KP5","KP5"),
					(C8.pack "NP5","KP5"),
					(C8.pack "WP5","KP5"),
					(C8.pack "LA","LA"),
					(C8.pack "LB","LA"),
					(C8.pack "LC","LA"),
					(C8.pack "LD","LA"),
					(C8.pack "LE","LA"),
					(C8.pack "LF","LA"),
					(C8.pack "LG","LA"),
					(C8.pack "LH","LA"),
					(C8.pack "LI","LA"),
					(C8.pack "LJ","LA"),
					(C8.pack "LK","LA"),
					(C8.pack "LL","LA"),
					(C8.pack "LM","LA"),
					(C8.pack "LN","LA"),
					(C8.pack "AY","LU"),
					(C8.pack "AZ","LU"),
					(C8.pack "L1","LU"),
					(C8.pack "L2","LU"),
					(C8.pack "L3","LU"),
					(C8.pack "L4","LU"),
					(C8.pack "L5","LU"),
					(C8.pack "L6","LU"),
					(C8.pack "L7","LU"),
					(C8.pack "L8","LU"),
					(C8.pack "L9","LU"),
					(C8.pack "LO","LU"),
					(C8.pack "LP","LU"),
					(C8.pack "LQ","LU"),
					(C8.pack "LR","LU"),
					(C8.pack "LS","LU"),
					(C8.pack "LT","LU"),
					(C8.pack "LU","LU"),
					(C8.pack "LV","LU"),
					(C8.pack "LW","LU"),
					(C8.pack "LX","LX"),
					(C8.pack "LY","LY"),
					(C8.pack "LZ","LZ"),
					(C8.pack "4T","OA"),
					(C8.pack "OA","OA"),
					(C8.pack "OB","OA"),
					(C8.pack "OC","OA"),
					(C8.pack "OD","OD"),
					(C8.pack "4U1V","OE"),
					(C8.pack "OE","OE"),
					(C8.pack "OF","OH"),
					(C8.pack "OG","OH"),
					(C8.pack "OH","OH"),
					(C8.pack "OI","OH"),
					(C8.pack "OJ","OH"),
					(C8.pack "OF0","OH0"),
					(C8.pack "OG0","OH0"),
					(C8.pack "OH0","OH0"),
					(C8.pack "OI0","OH0"),
					(C8.pack "OJ0","OJ0"),
					(C8.pack "OK","OK"),
					(C8.pack "OL","OK"),
					(C8.pack "OM","OM"),
					(C8.pack "ON","ON"),
					(C8.pack "OO","ON"),
					(C8.pack "OP","ON"),
					(C8.pack "OQ","ON"),
					(C8.pack "OR","ON"),
					(C8.pack "OS","ON"),
					(C8.pack "OT","ON"),
					(C8.pack "OX","OX"),
					(C8.pack "XP","OX"),
					(C8.pack "OW","OY"),
					(C8.pack "OY","OY"),
					(C8.pack "5P","OZ"),
					(C8.pack "5Q","OZ"),
					(C8.pack "OU","OZ"),
					(C8.pack "OV","OZ"),
					(C8.pack "OZ","OZ"),
					(C8.pack "P2","P2"),
					(C8.pack "P4","P4"),
					(C8.pack "HM","P5"),
					(C8.pack "P5","P5"),
					(C8.pack "P6","P5"),
					(C8.pack "P7","P5"),
					(C8.pack "P8","P5"),
					(C8.pack "P9","P5"),
					(C8.pack "PA","PA"),
					(C8.pack "PB","PA"),
					(C8.pack "PC","PA"),
					(C8.pack "PD","PA"),
					(C8.pack "PE","PA"),
					(C8.pack "PF","PA"),
					(C8.pack "PG","PA"),
					(C8.pack "PH","PA"),
					(C8.pack "PI","PA"),
					(C8.pack "PJ2","PJ2"),
					(C8.pack "PJ4","PJ4"),
					(C8.pack "PJ5","PJ5"),
					(C8.pack "PJ6","PJ5"),
					(C8.pack "PJ7","PJ7"),
					(C8.pack "PP","PY"),
					(C8.pack "PQ","PY"),
					(C8.pack "PR","PY"),
					(C8.pack "PS","PY"),
					(C8.pack "PT","PY"),
					(C8.pack "PU","PY"),
					(C8.pack "PV","PY"),
					(C8.pack "PW","PY"),
					(C8.pack "PX","PY"),
					(C8.pack "PY","PY"),
					(C8.pack "ZV","PY"),
					(C8.pack "ZW","PY"),
					(C8.pack "ZX","PY"),
					(C8.pack "ZY","PY"),
					(C8.pack "ZZ","PY"),
					(C8.pack "PP0F","PY0F"),
					(C8.pack "PQ0F","PY0F"),
					(C8.pack "PR0F","PY0F"),
					(C8.pack "PS0F","PY0F"),
					(C8.pack "PT0F","PY0F"),
					(C8.pack "PU0F","PY0F"),
					(C8.pack "PV0F","PY0F"),
					(C8.pack "PW0F","PY0F"),
					(C8.pack "PX0F","PY0F"),
					(C8.pack "PY0F","PY0F"),
					(C8.pack "PY0Z","PY0F"),
					(C8.pack "ZV0F","PY0F"),
					(C8.pack "ZW0F","PY0F"),
					(C8.pack "ZX0F","PY0F"),
					(C8.pack "ZY0F","PY0F"),
					(C8.pack "ZY0R","PY0F"),
					(C8.pack "ZY0Z","PY0F"),
					(C8.pack "ZZ0F","PY0F"),
					(C8.pack "PP0S","PY0S"),
					(C8.pack "PQ0S","PY0S"),
					(C8.pack "PR0S","PY0S"),
					(C8.pack "PS0S","PY0S"),
					(C8.pack "PT0S","PY0S"),
					(C8.pack "PU0S","PY0S"),
					(C8.pack "PV0S","PY0S"),
					(C8.pack "PW0S","PY0S"),
					(C8.pack "PX0S","PY0S"),
					(C8.pack "PY0S","PY0S"),
					(C8.pack "ZV0S","PY0S"),
					(C8.pack "ZW0S","PY0S"),
					(C8.pack "ZX0S","PY0S"),
					(C8.pack "ZY0S","PY0S"),
					(C8.pack "ZZ0S","PY0S"),
					(C8.pack "PP0M","PY0T"),
					(C8.pack "PP0T","PY0T"),
					(C8.pack "PQ0M","PY0T"),
					(C8.pack "PQ0T","PY0T"),
					(C8.pack "PR0M","PY0T"),
					(C8.pack "PR0T","PY0T"),
					(C8.pack "PS0M","PY0T"),
					(C8.pack "PS0T","PY0T"),
					(C8.pack "PT0M","PY0T"),
					(C8.pack "PT0T","PY0T"),
					(C8.pack "PU0M","PY0T"),
					(C8.pack "PU0T","PY0T"),
					(C8.pack "PV0M","PY0T"),
					(C8.pack "PV0T","PY0T"),
					(C8.pack "PW0M","PY0T"),
					(C8.pack "PW0T","PY0T"),
					(C8.pack "PX0M","PY0T"),
					(C8.pack "PX0T","PY0T"),
					(C8.pack "PY0M","PY0T"),
					(C8.pack "PY0T","PY0T"),
					(C8.pack "ZV0M","PY0T"),
					(C8.pack "ZV0T","PY0T"),
					(C8.pack "ZW0M","PY0T"),
					(C8.pack "ZW0T","PY0T"),
					(C8.pack "ZX0M","PY0T"),
					(C8.pack "ZX0T","PY0T"),
					(C8.pack "ZY0M","PY0T"),
					(C8.pack "ZY0T","PY0T"),
					(C8.pack "ZZ0M","PY0T"),
					(C8.pack "ZZ0T","PY0T"),
					(C8.pack "PZ","PZ"),
					(C8.pack "R1FJ","R1FJ"),
					(C8.pack "RI1FJ","R1FJ"),
					(C8.pack "FJL","R1FJ"),
					(C8.pack "S0","S0"),
					(C8.pack "S2","S2"),
					(C8.pack "S3","S2"),
					(C8.pack "S5","S5"),
					(C8.pack "S7","S7"),
					(C8.pack "S9","S9"),
					(C8.pack "7S","SM"),
					(C8.pack "8S","SM"),
					(C8.pack "SA","SM"),
					(C8.pack "SB","SM"),
					(C8.pack "SC","SM"),
					(C8.pack "SD","SM"),
					(C8.pack "SE","SM"),
					(C8.pack "SF","SM"),
					(C8.pack "SG","SM"),
					(C8.pack "SH","SM"),
					(C8.pack "SI","SM"),
					(C8.pack "SJ","SM"),
					(C8.pack "SK","SM"),
					(C8.pack "SL","SM"),
					(C8.pack "SM","SM"),
					(C8.pack "3Z","SP"),
					(C8.pack "HF","SP"),
					(C8.pack "SN","SP"),
					(C8.pack "SO","SP"),
					(C8.pack "SP","SP"),
					(C8.pack "SQ","SP"),
					(C8.pack "SR","SP"),
					(C8.pack "6T","ST"),
					(C8.pack "6U","ST"),
					(C8.pack "ST","ST"),
					(C8.pack "6A","SU"),
					(C8.pack "6B","SU"),
					(C8.pack "SS","SU"),
					(C8.pack "SU","SU"),
					(C8.pack "J4","SV"),
					(C8.pack "SV","SV"),
					(C8.pack "SW","SV"),
					(C8.pack "SX","SV"),
					(C8.pack "SY","SV"),
					(C8.pack "SZ","SV"),
					(C8.pack "J45","SV5"),
					(C8.pack "SV5","SV5"),
					(C8.pack "SW5","SV5"),
					(C8.pack "SX5","SV5"),
					(C8.pack "SY5","SV5"),
					(C8.pack "SZ5","SV5"),
					(C8.pack "J49","SV9"),
					(C8.pack "SV9","SV9"),
					(C8.pack "SW9","SV9"),
					(C8.pack "SX9","SV9"),
					(C8.pack "SY9","SV9"),
					(C8.pack "SZ9","SV9"),
					(C8.pack "T2","T2"),
					(C8.pack "T30","T30"),
					(C8.pack "T31","T31"),
					(C8.pack "T32","T32"),
					(C8.pack "T33","T33"),
					(C8.pack "60","T5"),
					(C8.pack "T5","T5"),
					(C8.pack "T7","T7"),
					(C8.pack "T8","T8"),
					(C8.pack "TA","TA"),
					(C8.pack "TB","TA"),
					(C8.pack "TC","TA"),
					(C8.pack "YM","TA"),
					(C8.pack "TA1","TA1"),
					(C8.pack "TB1","TA1"),
					(C8.pack "TC1","TA1"),
					(C8.pack "YM1","TA1"),
					(C8.pack "TF","TF"),
					(C8.pack "TD","TG"),
					(C8.pack "TG","TG"),
					(C8.pack "TE","TI"),
					(C8.pack "TI","TI"),
					(C8.pack "TE9","TI9"),
					(C8.pack "TI9","TI9"),
					(C8.pack "TJ","TJ"),
					(C8.pack "TK","TK"),
					(C8.pack "TL","TL"),
					(C8.pack "TN","TN"),
					(C8.pack "TR","TR"),
					(C8.pack "TT","TT"),
					(C8.pack "TU","TU"),
					(C8.pack "TY","TY"),
					(C8.pack "TZ","TZ"),
					(C8.pack "R","UA"),
					(C8.pack "U","UA"),
					(C8.pack "R2F","UA2"),
					(C8.pack "R2K","UA2"),
					(C8.pack "RA2","UA2"),
					(C8.pack "RC2F","UA2"),
					(C8.pack "RC2K","UA2"),
					(C8.pack "RD2F","UA2"),
					(C8.pack "RD2K","UA2"),
					(C8.pack "RF2F","UA2"),
					(C8.pack "RF2K","UA2"),
					(C8.pack "RG2F","UA2"),
					(C8.pack "RG2K","UA2"),
					(C8.pack "RI2F","UA2"),
					(C8.pack "RI2K","UA2"),
					(C8.pack "RJ2F","UA2"),
					(C8.pack "RJ2K","UA2"),
					(C8.pack "RK2F","UA2"),
					(C8.pack "RK2K","UA2"),
					(C8.pack "RL2F","UA2"),
					(C8.pack "RL2K","UA2"),
					(C8.pack "RM2F","UA2"),
					(C8.pack "RM2K","UA2"),
					(C8.pack "RN2F","UA2"),
					(C8.pack "RN2K","UA2"),
					(C8.pack "RO2F","UA2"),
					(C8.pack "RO2K","UA2"),
					(C8.pack "RP2F","UA2"),
					(C8.pack "RP2K","UA2"),
					(C8.pack "RQ2F","UA2"),
					(C8.pack "RQ2K","UA2"),
					(C8.pack "RR2F","UA2"),
					(C8.pack "RR2K","UA2"),
					(C8.pack "RT2F","UA2"),
					(C8.pack "RT2K","UA2"),
					(C8.pack "RU2F","UA2"),
					(C8.pack "RU2K","UA2"),
					(C8.pack "RV2F","UA2"),
					(C8.pack "RV2K","UA2"),
					(C8.pack "RW2F","UA2"),
					(C8.pack "RW2K","UA2"),
					(C8.pack "RX2F","UA2"),
					(C8.pack "RX2K","UA2"),
					(C8.pack "RY2F","UA2"),
					(C8.pack "RY2K","UA2"),
					(C8.pack "RZ2F","UA2"),
					(C8.pack "RZ2K","UA2"),
					(C8.pack "U2F","UA2"),
					(C8.pack "U2K","UA2"),
					(C8.pack "UA2","UA2"),
					(C8.pack "UB2","UA2"),
					(C8.pack "UC2","UA2"),
					(C8.pack "UD2","UA2"),
					(C8.pack "UE2","UA2"),
					(C8.pack "UF2","UA2"),
					(C8.pack "UG2","UA2"),
					(C8.pack "UH2","UA2"),
					(C8.pack "UI2","UA2"),
					(C8.pack "R0","UA9"),
					(C8.pack "R8","UA9"),
					(C8.pack "R9","UA9"),
					(C8.pack "U0","UA9"),
					(C8.pack "U8","UA9"),
					(C8.pack "U9","UA9"),
					(C8.pack "UA9","UA9"),
					(C8.pack "UB9","UA9"),
					(C8.pack "UC9","UA9"),
					(C8.pack "UD9","UA9"),
					(C8.pack "UE9","UA9"),
					(C8.pack "UF9","UA9"),
					(C8.pack "UG9","UA9"),
					(C8.pack "UH9","UA9"),
					(C8.pack "UI9","UA9"),
					(C8.pack "UA0","UA9"),
					(C8.pack "UB0","UA9"),
					(C8.pack "UC0","UA9"),
					(C8.pack "UD0","UA9"),
					(C8.pack "UE0","UA9"),
					(C8.pack "UF0","UA9"),
					(C8.pack "UG0","UA9"),
					(C8.pack "UH0","UA9"),
					(C8.pack "UI0","UA9"),
					(C8.pack "UA8","UA9"),
					(C8.pack "UB8","UA9"),
					(C8.pack "UC8","UA9"),
					(C8.pack "UD8","UA9"),
					(C8.pack "UE8","UA9"),
					(C8.pack "UF8","UA9"),
					(C8.pack "UG8","UA9"),
					(C8.pack "UH8","UA9"),
					(C8.pack "UI8","UA9"),
					(C8.pack "RA9","UA9"),
					(C8.pack "RB9","UA9"),
					(C8.pack "RC9","UA9"),
					(C8.pack "RD9","UA9"),
					(C8.pack "RE9","UA9"),
					(C8.pack "RF9","UA9"),
					(C8.pack "RG9","UA9"),
					(C8.pack "RH9","UA9"),
					(C8.pack "RI9","UA9"),
					(C8.pack "RJ9","UA9"),
					(C8.pack "RK9","UA9"),
					(C8.pack "RL9","UA9"),
					(C8.pack "RM9","UA9"),
					(C8.pack "RN9","UA9"),
					(C8.pack "RO9","UA9"),
					(C8.pack "RP9","UA9"),
					(C8.pack "RQ9","UA9"),
					(C8.pack "RR9","UA9"),
					(C8.pack "RS9","UA9"),
					(C8.pack "RT9","UA9"),
					(C8.pack "RU9","UA9"),
					(C8.pack "RV9","UA9"),
					(C8.pack "RW9","UA9"),
					(C8.pack "RX9","UA9"),
					(C8.pack "RY9","UA9"),
					(C8.pack "RZ9","UA9"),
					(C8.pack "RA0","UA9"),
					(C8.pack "RB0","UA9"),
					(C8.pack "RC0","UA9"),
					(C8.pack "RD0","UA9"),
					(C8.pack "RE0","UA9"),
					(C8.pack "RF0","UA9"),
					(C8.pack "RG0","UA9"),
					(C8.pack "RH0","UA9"),
					(C8.pack "RI0","UA9"),
					(C8.pack "RJ0","UA9"),
					(C8.pack "RK0","UA9"),
					(C8.pack "RL0","UA9"),
					(C8.pack "RM0","UA9"),
					(C8.pack "RN0","UA9"),
					(C8.pack "RO0","UA9"),
					(C8.pack "RP0","UA9"),
					(C8.pack "RQ0","UA9"),
					(C8.pack "RR0","UA9"),
					(C8.pack "RS0","UA9"),
					(C8.pack "RT0","UA9"),
					(C8.pack "RU0","UA9"),
					(C8.pack "RV0","UA9"),
					(C8.pack "RW0","UA9"),
					(C8.pack "RX0","UA9"),
					(C8.pack "RY0","UA9"),
					(C8.pack "RZ0","UA9"),
					(C8.pack "RA8","UA9"),
					(C8.pack "RB8","UA9"),
					(C8.pack "RC8","UA9"),
					(C8.pack "RD8","UA9"),
					(C8.pack "RE8","UA9"),
					(C8.pack "RF8","UA9"),
					(C8.pack "RG8","UA9"),
					(C8.pack "RH8","UA9"),
					(C8.pack "RI8","UA9"),
					(C8.pack "RJ8","UA9"),
					(C8.pack "RK8","UA9"),
					(C8.pack "RL8","UA9"),
					(C8.pack "RM8","UA9"),
					(C8.pack "RN8","UA9"),
					(C8.pack "RO8","UA9"),
					(C8.pack "RP8","UA9"),
					(C8.pack "RQ8","UA9"),
					(C8.pack "RR8","UA9"),
					(C8.pack "RS8","UA9"),
					(C8.pack "RT8","UA9"),
					(C8.pack "RU8","UA9"),
					(C8.pack "RV8","UA9"),
					(C8.pack "RW8","UA9"),
					(C8.pack "RX8","UA9"),
					(C8.pack "RY8","UA9"),
					(C8.pack "RZ8","UA9"),
					(C8.pack "UJ","UK"),
					(C8.pack "UK","UK"),
					(C8.pack "UL","UK"),
					(C8.pack "UM","UK"),
					(C8.pack "UN","UN"),
					(C8.pack "UO","UN"),
					(C8.pack "UP","UN"),
					(C8.pack "UQ","UN"),
					(C8.pack "EM","UR"),
					(C8.pack "EN","UR"),
					(C8.pack "EO","UR"),
					(C8.pack "U5","UR"),
					(C8.pack "UR","UR"),
					(C8.pack "US","UR"),
					(C8.pack "UT","UR"),
					(C8.pack "UU","UR"),
					(C8.pack "UV","UR"),
					(C8.pack "UW","UR"),
					(C8.pack "UX","UR"),
					(C8.pack "UY","UR"),
					(C8.pack "UZ","UR"),
					(C8.pack "V2","V2"),
					(C8.pack "V3","V3"),
					(C8.pack "V4","V4"),
					(C8.pack "V5","V5"),
					(C8.pack "V6","V6"),
					(C8.pack "V7","V7"),
					(C8.pack "V8","V8"),
					(C8.pack "CF","VE"),
					(C8.pack "CG","VE"),
					(C8.pack "CJ","VE"),
					(C8.pack "CK","VE"),
					(C8.pack "VA","VE"),
					(C8.pack "VB","VE"),
					(C8.pack "VC","VE"),
					(C8.pack "VE","VE"),
					(C8.pack "VG","VE"),
					(C8.pack "VX","VE"),
					(C8.pack "XL","VE"),
					(C8.pack "XM","VE"),
					(C8.pack "CH1","VE"),
					(C8.pack "CH2","VE"),
					(C8.pack "CI0","VE"),
					(C8.pack "CI1","VE"),
					(C8.pack "CI2","VE"),
					(C8.pack "CY1","VE"),
					(C8.pack "CY2","VE"),
					(C8.pack "CZ0","VE"),
					(C8.pack "CZ1","VE"),
					(C8.pack "CZ2","VE"),
					(C8.pack "VD1","VE"),
					(C8.pack "VD2","VE"),
					(C8.pack "VF0","VE"),
					(C8.pack "VF1","VE"),
					(C8.pack "VF2","VE"),
					(C8.pack "VG2","VE"),
					(C8.pack "VO1","VE"),
					(C8.pack "VO2","VE"),
					(C8.pack "VY0","VE"),
					(C8.pack "VY1","VE"),
					(C8.pack "VY2","VE"),
					(C8.pack "XJ1","VE"),
					(C8.pack "XJ2","VE"),
					(C8.pack "XK0","VE"),
					(C8.pack "XK1","VE"),
					(C8.pack "XK2","VE"),
					(C8.pack "XN1","VE"),
					(C8.pack "XN2","VE"),
					(C8.pack "XO0","VE"),
					(C8.pack "XO1","VE"),
					(C8.pack "XO2","VE"),
					(C8.pack "AX","VK"),
					(C8.pack "VH","VK"),
					(C8.pack "VI","VK"),
					(C8.pack "VJ","VK"),
					(C8.pack "VK","VK"),
					(C8.pack "VL","VK"),
					(C8.pack "VM","VK"),
					(C8.pack "VN","VK"),
					(C8.pack "VZ","VK"),
					(C8.pack "AX9C","VK9C"),
					(C8.pack "AX9Y","VK9C"),
					(C8.pack "VH9C","VK9C"),
					(C8.pack "VH9Y","VK9C"),
					(C8.pack "VI9C","VK9C"),
					(C8.pack "VI9Y","VK9C"),
					(C8.pack "VJ9C","VK9C"),
					(C8.pack "VJ9Y","VK9C"),
					(C8.pack "VK9C","VK9C"),
					(C8.pack "VK9Y","VK9C"),
					(C8.pack "VL9C","VK9C"),
					(C8.pack "VL9Y","VK9C"),
					(C8.pack "VM9C","VK9C"),
					(C8.pack "VM9Y","VK9C"),
					(C8.pack "VN9C","VK9C"),
					(C8.pack "VN9Y","VK9C"),
					(C8.pack "VZ9C","VK9C"),
					(C8.pack "VZ9Y","VK9C"),
					(C8.pack "AX9L","VK9L"),
					(C8.pack "VH9L","VK9L"),
					(C8.pack "VI9L","VK9L"),
					(C8.pack "VJ9L","VK9L"),
					(C8.pack "VK9L","VK9L"),
					(C8.pack "VL9L","VK9L"),
					(C8.pack "VM9L","VK9L"),
					(C8.pack "VN9L","VK9L"),
					(C8.pack "VZ9L","VK9L"),
					(C8.pack "AX9M","VK9M"),
					(C8.pack "VH9M","VK9M"),
					(C8.pack "VI9M","VK9M"),
					(C8.pack "VJ9M","VK9M"),
					(C8.pack "VK9M","VK9M"),
					(C8.pack "VL9M","VK9M"),
					(C8.pack "VM9M","VK9M"),
					(C8.pack "VN9M","VK9M"),
					(C8.pack "VZ9M","VK9M"),
					(C8.pack "AX9","VK9N"),
					(C8.pack "VH9","VK9N"),
					(C8.pack "VI9","VK9N"),
					(C8.pack "VJ9","VK9N"),
					(C8.pack "VK9","VK9N"),
					(C8.pack "VL9","VK9N"),
					(C8.pack "VM9","VK9N"),
					(C8.pack "VN9","VK9N"),
					(C8.pack "VZ9","VK9N"),
					(C8.pack "AX9W","VK9W"),
					(C8.pack "AX9Z","VK9W"),
					(C8.pack "VH9W","VK9W"),
					(C8.pack "VH9Z","VK9W"),
					(C8.pack "VI9W","VK9W"),
					(C8.pack "VI9Z","VK9W"),
					(C8.pack "VJ9W","VK9W"),
					(C8.pack "VJ9Z","VK9W"),
					(C8.pack "VK9W","VK9W"),
					(C8.pack "VK9Z","VK9W"),
					(C8.pack "VL9W","VK9W"),
					(C8.pack "VL9Z","VK9W"),
					(C8.pack "VM9W","VK9W"),
					(C8.pack "VM9Z","VK9W"),
					(C8.pack "VN9W","VK9W"),
					(C8.pack "VN9Z","VK9W"),
					(C8.pack "VZ9W","VK9W"),
					(C8.pack "VZ9Z","VK9W"),
					(C8.pack "AX9X","VK9X"),
					(C8.pack "VH9X","VK9X"),
					(C8.pack "VI9X","VK9X"),
					(C8.pack "VJ9X","VK9X"),
					(C8.pack "VK9X","VK9X"),
					(C8.pack "VL9X","VK9X"),
					(C8.pack "VM9X","VK9X"),
					(C8.pack "VN9X","VK9X"),
					(C8.pack "VZ9X","VK9X"),
					(C8.pack "VP2E","VP2E"),
					(C8.pack "VP2M","VP2M"),
					(C8.pack "VP2V","VP2V"),
					(C8.pack "VP5","VP5"),
					(C8.pack "VP5","VQ5"),
					(C8.pack "VP6","VP6"),
					(C8.pack "VP8","VP8"),
					(C8.pack "CE9","VP8/h"),
					(C8.pack "XR9","VP8/h"),
					(C8.pack "VP9","VP9"),
					(C8.pack "VQ9","VQ9"),
					(C8.pack "VR","VR"),
					(C8.pack "8T","VU"),
					(C8.pack "8U","VU"),
					(C8.pack "8V","VU"),
					(C8.pack "8W","VU"),
					(C8.pack "8X","VU"),
					(C8.pack "8Y","VU"),
					(C8.pack "AT","VU"),
					(C8.pack "AU","VU"),
					(C8.pack "AV","VU"),
					(C8.pack "AW","VU"),
					(C8.pack "VT","VU"),
					(C8.pack "VU","VU"),
					(C8.pack "VV","VU"),
					(C8.pack "VW","VU"),
					(C8.pack "VU4","VU4"),
					(C8.pack "VU7","VU7"),
					(C8.pack "4A","XE"),
					(C8.pack "4B","XE"),
					(C8.pack "4C","XE"),
					(C8.pack "6D","XE"),
					(C8.pack "6E","XE"),
					(C8.pack "6F","XE"),
					(C8.pack "6G","XE"),
					(C8.pack "6H","XE"),
					(C8.pack "6I","XE"),
					(C8.pack "6J","XE"),
					(C8.pack "XA","XE"),
					(C8.pack "XB","XE"),
					(C8.pack "XC","XE"),
					(C8.pack "XD","XE"),
					(C8.pack "XE","XE"),
					(C8.pack "XF","XE"),
					(C8.pack "XG","XE"),
					(C8.pack "XH","XE"),
					(C8.pack "XI","XE"),
					(C8.pack "4A4","XF4"),
					(C8.pack "4B4","XF4"),
					(C8.pack "4C4","XF4"),
					(C8.pack "6D4","XF4"),
					(C8.pack "6E4","XF4"),
					(C8.pack "6F4","XF4"),
					(C8.pack "6G4","XF4"),
					(C8.pack "6H4","XF4"),
					(C8.pack "6I4","XF4"),
					(C8.pack "6J4","XF4"),
					(C8.pack "XA4","XF4"),
					(C8.pack "XB4","XF4"),
					(C8.pack "XC4","XF4"),
					(C8.pack "XD4","XF4"),
					(C8.pack "XE4","XF4"),
					(C8.pack "XF0","XF4"),
					(C8.pack "XF4","XF4"),
					(C8.pack "XG4","XF4"),
					(C8.pack "XH4","XF4"),
					(C8.pack "XI4","XF4"),
					(C8.pack "XT","XT"),
					(C8.pack "XU","XU"),
					(C8.pack "XW","XW"),
					(C8.pack "XX9","XX9"),
					(C8.pack "XY","XZ"),
					(C8.pack "XZ","XZ"),
					(C8.pack "T6","YA"),
					(C8.pack "YA","YA"),
					(C8.pack "7A","YB"),
					(C8.pack "7B","YB"),
					(C8.pack "7C","YB"),
					(C8.pack "7D","YB"),
					(C8.pack "7E","YB"),
					(C8.pack "7F","YB"),
					(C8.pack "7G","YB"),
					(C8.pack "7H","YB"),
					(C8.pack "7I","YB"),
					(C8.pack "8A","YB"),
					(C8.pack "8B","YB"),
					(C8.pack "8C","YB"),
					(C8.pack "8D","YB"),
					(C8.pack "8E","YB"),
					(C8.pack "8F","YB"),
					(C8.pack "8G","YB"),
					(C8.pack "8H","YB"),
					(C8.pack "8I","YB"),
					(C8.pack "JZ","YB"),
					(C8.pack "PK","YB"),
					(C8.pack "PL","YB"),
					(C8.pack "PM","YB"),
					(C8.pack "PN","YB"),
					(C8.pack "PO","YB"),
					(C8.pack "YB","YB"),
					(C8.pack "YC","YB"),
					(C8.pack "YD","YB"),
					(C8.pack "YE","YB"),
					(C8.pack "YF","YB"),
					(C8.pack "YG","YB"),
					(C8.pack "YH","YB"),
					(C8.pack "HN","YI"),
					(C8.pack "YI","YI"),
					(C8.pack "YJ","YJ"),
					(C8.pack "6C","YK"),
					(C8.pack "YK","YK"),
					(C8.pack "YL","YL"),
					(C8.pack "H6","YN"),
					(C8.pack "H7","YN"),
					(C8.pack "HT","YN"),
					(C8.pack "YN","YN"),
					(C8.pack "YO","YO"),
					(C8.pack "YP","YO"),
					(C8.pack "YQ","YO"),
					(C8.pack "YR","YO"),
					(C8.pack "HU","YS"),
					(C8.pack "YS","YS"),
					(C8.pack "4N","YU"),
					(C8.pack "YT","YU"),
					(C8.pack "YU","YU"),
					(C8.pack "4M","YV"),
					(C8.pack "YV","YV"),
					(C8.pack "YW","YV"),
					(C8.pack "YX","YV"),
					(C8.pack "YY","YV"),
					(C8.pack "4M0","YV0"),
					(C8.pack "YV0","YV0"),
					(C8.pack "YW0","YV0"),
					(C8.pack "YX0","YV0"),
					(C8.pack "YY0","YV0"),
					(C8.pack "Z2","Z2"),
					(C8.pack "Z3","Z3"),
					(C8.pack "Z6","Z6"),
					(C8.pack "Z8","Z8"),
					(C8.pack "ZA","ZA"),
					(C8.pack "ZB","ZB"),
					(C8.pack "ZG","ZB"),
					(C8.pack "ZC4","ZC4"),
					(C8.pack "ZD7","ZD7"),
					(C8.pack "ZD8","ZD8"),
					(C8.pack "ZD9","ZD9"),
					(C8.pack "ZF","ZF"),
					(C8.pack "ZK3","ZK3"),
					(C8.pack "ZK","ZL"),
					(C8.pack "ZL","ZL"),
					(C8.pack "ZM","ZL"),
					(C8.pack "ZL7","ZL7"),
					(C8.pack "ZM7","ZL7"),
					(C8.pack "ZL8","ZL8"),
					(C8.pack "ZM8","ZL8"),
					(C8.pack "ZL9","ZL9"),
					(C8.pack "ZM9","ZL9"),
					(C8.pack "ZP","ZP"),
					(C8.pack "H5","ZS"),
					(C8.pack "S4","ZS"),
					(C8.pack "S8","ZS"),
					(C8.pack "V9","ZS"),
					(C8.pack "ZR","ZS"),
					(C8.pack "ZS","ZS"),
					(C8.pack "ZT","ZS"),
					(C8.pack "ZU","ZS"),
					(C8.pack "ZR8","ZS8"),
					(C8.pack "ZS8","ZS8"),
					(C8.pack "ZT8","ZS8"),
					(C8.pack "ZU8","ZS8")]
					
exactMapString = [("3D2/c",["3D20CR"]),
                  ("3D2/r",["3D2R","3D2RI"]),
                  ("3Y/b",["3Y0E"]),
                  ("3Y/p",["3Y0X"]),
                  ("4U1I",["4U1WRC"]),
                  ("7O",["7O6T"]),
                  ("9M2",["9M8DX/2"]),
                  ("9M6",["9M4CRB","9M4SAB"]),
                  ("A6",["A61BK/JJ"]),
                  ("BS7",["BS7H"]),
                  ("CE9",["K9PET/KC4","8J1RL","DP0GVN","DP0GVN/P","DP1POL","KC4AAA","KC4AAC","KC4USB","KC4USV","VP8ADE/B","VP8DMH","VU3BPZ","VU3BPZ/P"]),
                  ("E5/n",["E51M","E51WL"]),
                  ("FG",["TO22C","TO6D","TO66R"]),
                  ("FH",["TO7BC","TO0X"]),
                  ("FJ",["TO3X","TO3A","TO4K"]),
                  ("FK",["TX8NC","TX1CW","TX8B","TX8C","TX8D"]),
                  ("FK/c",["FK8IK/C"]),
                  ("FM",["TO5A","TO5K","TO5T","TO7A","TO9R","TO5X","TO2M","TO4GU","TO8M"]),
                  ("FO/a",["FO/F6CTL"]),
                  ("FO/c",["TX5C","TX5K"]),
                  ("FO/m",["TX7M","TX5A","TX7G"]),
                  ("FR",["TO2R","TO7CC","TO90R"]),
                  ("FS",["TO1E"]),
                  ("FY",["TO2A","TO1A"]),
                  ("GD",["2Q0YLX","GB2WB","GB5TD"]),
                  ("GI",["2Q0ETB","2Q0HRV","2Q0MFB","2Q0NIE","2Q0SXG","2Q0TWA","2Q0VEP","2Q0VIM","2Q0ZXM","GB0CHW","GB1SPD","GB2AD","GB2PP","GB4SPD","GB5SPD","GQ0AQD","GQ3KVD","GQ3SG","GQ4DOH","GQ4JTF","GQ4SZW","GQ7AXB","MQ0BPB","MQ0MOD","MQ0MSR","MQ0RRE","MQ0TGI","MQ6WAG","MQ6WDB"]),
                  ("GJ",["MQ0ASP"]),
                  ("GM",["GB0FFS","GB0SSB","GB100MUC","GB1KLD","GB1OL","GB2BHM","GB2CHC","GB2GNL","GB2LBN","GB2LT","GB2MOF","GB2MSL","GB2NCL","GB2OWM","GB2PG","GB2RWW","GB2SWF","GB2VCB","GB3SWF","GB4SWF","GB5AG","GB5FHC","GB5SI","GB80GD","GM6WRW/P","GQ0BKC","GQ0DBW","GQ0DEQ","GQ1BAN","GQ4EMX","GQ4JPZ","GQ4PRB","GQ4WZG","GQ4XQJ","GQ6KON","GQ8TTD","MM0YHB/P","MQ0GYX","MQ0GYX/P","MQ0XXW","MQ0ZBH","MQ6BJJ","MQ6KAU"]),
                  ("GM/s",["2M0ZET","2M1ANT","2M1ASQ","2M1ODL","G0FBJ","GB0HFC","GB0OS","GB2ELH","GB2WG","GB2ZET","GB4SI","GM0CXQ","GM0CYJ","GM0DJI","GM0EKM","GM0ILB","GM0JDB","GM0MZD","GM0OMV","GM0VFA","GM1BYL","GM1CBQ","GM1KKI","GM1MXN","GM1ZNR","GM3KLA","GM3RFR","GM3SJA","GM3STU","GM3UPU","GM3WCH","GM3WHT","GM3XPQ","GM3ZET","GM3ZNM","GM3ZXH","GM4AGX","GM4CAQ","GM4DQD","GM4ENK","GM4FNA","GM4FNE","GM4GPN","GM4GPP","GM4GQD","GM4GQM","GM4IPK","GM4JPI","GM4KJQ","GM4LBE","GM4LER","GM4PXG","GM4SLV","GM4SRU","GM4SSA","GM4SWU","GM4WXQ","GM4YEL","GM4ZHL","GM6RTO","GM6VZB","GM6WVI","GM6YQA","GM7AFE","GM7GWW","GM7RKD","GM8LNH","GM8MMA","GM8YEC","GS3ZET","MA1FJM","MM0LSM","MM0XAU","MM0ZAL","MM0ZCG","MM1FJM","MM3ZET","MM5PSL","MM6ACW","MM6SJK","MQ5PSL","MS0ZCG","MS0ZET"]),
                  ("GW",["2Q0DAA","2Q0WDS","GB0AD","GB0HEL","GB0HLT","GB0MPA","GB0NAW","GB0PLB","GB0RS","GB0WHR","GB100GGM","GB10SOTA","GB1CDS","GB1OOC","GB2GGM","GB2LSA","GB2MOP","GB2TD","GB4BPL","GB4MBC","GB4MD","GB4MDI","GB4SDD","GB5FI","GB5GEO","GB60DITP","GB6BLB","GB8MD","GQ0TQM","GQ0VKW","GQ1IOT","GQ4BKG","GQ4BLE","GQ4MVA","GQ6NKG","GQ7DWR","GQ8JOY","MQ0GXE","MQ0UPH","MQ0UPH/P","MQ1CFN","MQ1LCR","MQ3WPH","MQ3ZCB/P"]),
                  ("HK0/m",["HK0TU"]),
                  ("HZ",["HZ1SBS/J"]),
                  ("I",["4U1GSC","4U4F","I1YRL/GRA","4U0WFP","4U5F"]),
                  ("IS",["II0SB","IQ0AH","IQ0ID","IQ0SS","IY0GA"]),
                  ("IT9",["IT9CLY/JZK","IT9GDS/WLK","IT9JZK/WLK","IT9KKE/JZK","IT9OTF/JZK"]),
                  ("JD/m",["JD1/JF7MTO","JD1/JG8NQJ","JD1BME","JF7MTO/JD1","JG8NQJ/JD1"]),
                  ("JW/b",["JW4GHA"]),
                  ("KH2",["KG6DX"]),
                  ("KH3",["KJ6BZ"]),
                  ("KH6",["AH0A","K4XV","K6MKF","K9FD","KB6EGA","KL3FN","N6KB","NH2IF","W3GW","WB4JTT"]),
                  ("KH8/s",["KH8SI"]),
                  ("KL",["AH0AH","K7V","N7ZYS"]),
                  ("KP2",["K9VV","KV4BT","KV4BW","KV4CF","KV4FZ"]),
                  ("KP4",["KB2OPM","KC2TE","KH2RU","KP2Z","N2PGO"]),
                  ("LU",["LU1DCB/D","LU1DDK/D","LU1HLH/D","LU1UM/U","LU1XS/O","LU1XZ/H","LU2DJB/J","LU2DVI/H","LU2EDC/D","LU4DBT/D","LU4DLL/D","LU5DEM/W[16]","LU5DGI/W","LU5DX/H","LU5FZ/F","LU7DOT/D","LU7EPC/D","LU7HW/D","LU9DF/D","LU9JLV/J","LU9JMG/J","LW2ECK/D","LW2EIY/H","LW3DKO/D"]),
                  ("OH",["OH7QA/S"]),
                  ("PA",["PH4RTM/MILL","PH4RTM/WHE"]),
                  ("SV/a",["SV2ASP/A"]),            
				  ("TA",["TC50TRAC/01K","TC50TRAC/17B","TC50TRAC/28GR","TC50TRAC/41KF","TC50TRAC/01A","TC50TRAC/03D","TC50TRAC/10B","TC50TRAC/15B","TC50TRAC/16M","TC50TRAC/34K","TC50TRAC/35I","TC50TRAC/41G","TC50TRAC/41K","TC50TRAC/67E","TC50TRAC/67Z","TC50TRAC/80K","TC50TRAC/80O","TC5OTRAC/35K"]),
                  ("UA",["RP67KR"]),
                  ("UA2",["R2MWO"]),
                  ("UA9",["RP67GI","RP67MG","RP67MP","RP67NG","RP67RK","RP67ST","RP67SW","RP67UF","UE80C"]),
                  ("VK0H",["=VK0IR"]),
                  ("VK0M",["VK0TH"]),
                  ("VK9C",["VK9AA"]),
                  ("VK9L",["VK9FLHI","VK9PN"]),
                  ("VP6/d",["VP6DX"]),
                  ("VP8/g",["VP8SGK"]),
                  ("VP8/h",["HF0POL","RI1ANA","RI1ANF"]),
                  ("VP8/o",["LU1ZA"]),
                  ("VP8/s",["VP8THU"]),
                  ("Z6",["YU8/HB9BF"])]